### ISSUE TITLE
paths on windows (and dev support in general)

### ISSUE THREAD

**Issue by matanzg** [powmedia/mongoose-fixtures#29]
Hi,

On line 30 of mongoose_fixtures.js there's OS specific code:
```javascript
    //Get the absolute dir path if a relative path was given
    if (data.substr(0, 1) !== '/') {
```

I can't really use full, valid paths in Windows since the drive letter would be duplicated (e.g. c:\c:\test\fixture.js). 

I wanted to send a pull request, but I couldn't run the existing tests, as npm install tries to clone "git://github.com/OpenifyIt/commons.git" which doesn't seem to exist (am I missing something in the setup, or is it outdated?).

Thanks.

**Comment by fultonm** [comment]
Same
`1) Competition controller "before each" hook:
     Uncaught Error: ENOENT: no such file or directory, stat 'G:\G:\p\d2c\test\api\controllers\test\app\fixtures'
      at Error (native)`

**Comment by brano543** [comment]
You need to cut off the first three characters(Path_name:\) from the path string to make it work. Also you need to pass mongoose.connection as second parameter to fixtures.load function

fixtures.load(__dirname.substr(3) + '/model/your_collection.js', mongoose.connection, function(err) {
    console.log(err||'Fixtures loaded successfully!');
});

**Comment by matanzg** [comment]
Thanks for the workaround, we've actually already applied something similar, but I figured it would be nicer if the library was more OS independent. Also, I can't really contribute since the build process seems broken, which is also worth fixing.

**Comment by brano543** [comment]
Yes, i am looking up into it right now. I am testing on Windows, but my application is hosted on Linux. Will let you know when i figure out universal solution.

**Comment by brano543** [comment]
Okay, here is universal solution working for both Windows and Linux. Enjoy :)

var fixture_path = path.resolve('./model/film.js');
if (process.platform == "win32"){
    fixture_path = fixture_path.substr(3);
}

fixtures.load(fixture_path, db.connection, function(err) {
    console.log(err||'Fixtures loaded successfully!');
});

**Comment by matanzg** [comment]
That's actually almost exactly what we did :)

While I appreciate you providing a great workaround, and we can close this issue if you'd like, I think a better solution would be to perform this test within the library itself (as I wished to to in a pull request).

**Comment by brano543** [comment]
If you wish to fix the tests, you need to use the new version of that MongooseInitializer that was used there,its located here now https://github.com/snailjs/apx-mongoose and also rework the tests accordingly.
