### ISSUE TITLE
TypeError: Cannot read property 'model' of undefined

### ISSUE THREAD

**Issue by m3l7** [powmedia/mongoose-fixtures#32]
hello, 
I'm trying to load a file, and I get:

      TypeError: Cannot read property 'model' of undefined

I'm using pow-mongoose-fixtures 0.3.0.

It turns out that on line 18:

     if (typeof db === 'function') {
        callback = db;
        db = mongoose.connection;
    }

this block is never called if I don't specified other that 1 parameters to load method.

typeof db in my case is always "undefined". 

Is that because I'm using typescript?

**Comment by powmedia** [comment]
How are you calling the method?  You need at least 2 arguments: data and callback

**Comment by m3l7** [comment]
With 2 arguments it's working.

I used only 1 argument as the readme suggests. Is the readme outdated?

**Comment by powmedia** [comment]
Yes but I've updated it now
